language: java
jdk:
 - oraclejdk8
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: TipInstituto

# - chmod +x ./mvnw
# - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
