language: java
sudo: true
dist: trusty
jdk: oraclejdk9
addons:
apt:
packages:
- oracle-java9-installer
before_install:

# - chmod +x ./mvnw
# - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar