version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: tip-instituto
      MYSQL_USER: Santiago
      MYSQL_PASSWORD: 33269447
      MYSQL_ROOT_PASSWORD: 33269447
    volumes:
      - db-data:/var/lib/mysql

  app-server:
    build: ./server
    ports:
      - '9000:8080'
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db/tip-instituto?useSSL=false&serverTimezone=GMT-3
      SPRING_DATASOURCE_USERNAME: Santiago
      SPRING_DATASOURCE_PASSWORD: 33269447

  inst-prod:
    container_name: inst-prod
    restart: always
    depends_on:
      - app-server
    build:
      context: ./client
    environment:
        API_BASE_URL: http://127.0.0.1:9000/api
    ports:
      - '80:80'

volumes:
  db-data:

