version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_DATABASE: tip-instituto
      MYSQL_USER: Santiago
      MYSQL_PASSWORD: 33269447
      MYSQL_ROOT_PASSWORD: 33269447
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  app-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:8080/tip-instituto?useSSL=false&serverTimezone=GMT-3
      SPRING_DATASOURCE_USERNAME: Santiago
      SPRING_DATASOURCE_PASSWORD: 33269447
    networks:
      - backend
      - frontend

  inst-prod:
    container_name: inst-prod
    restart: always
    depends_on:
      - app-server
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        #REACT_APP_API_BASE_URL: http://127.0.0.1:8080/
        PROXY_API = "http://app-server:8080"
        ports:
      - '80:80'
    networks:
      - frontend

volumes:
  db-data:

networks:
  backend:
  frontend:
