version: '3'

services:
  server:
    image: springboot-docker-compose-app:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/springboot-docker-compose-app
    ports:
      - "8081:8081"

  client:
    container_name: inst_client
    restart: always
   depends_on:
     - server
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - '.:/client'
      - '/client/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
