image: docker:latest

services:
  - docker:dind

stages:
  - build

before_script:
  - export IMAGE_TAG="$CI_COMMIT_REF_NAME"
  - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY

docker:
  stage: build
  script:
    - docker build --pull -f Dockerfile -t "${CI_REGISTRY_IMAGE}:${IMAGE_TAG}" .
    - docker push "${CI_REGISTRY_IMAGE}:${IMAGE_TAG}"
  only:
    - /^\d+\.\d+/

